//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteMjr.Domain {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class MjrSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static MjrSettings defaultInstance = ((MjrSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MjrSettings())));
        
        public static MjrSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CanCheckinToolBetweenCompanies {
            get {
                return ((bool)(this["CanCheckinToolBetweenCompanies"]));
            }
            set{
                this["CanCheckinToolBetweenCompanies"] = value;
            }
        }
    }
}
