// <auto-generated />
namespace WebSiteMjr.EfConfigurationMigrationData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class SenaIdRelation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SenaIdRelation));
        
        string IMigrationMetadata.Id
        {
            get { return "201506091402115_SenaIdRelation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
