// <auto-generated />
namespace WebSiteMjr.EfConfigurationMigrationData.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Tool : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tool));
        
        string IMigrationMetadata.Id
        {
            get { return "201312081448588_Tool"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
