// <auto-generated />
namespace WebSiteMjr.EfConfigurationMigrationData.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class RecreateCompaniesAndEmployeesTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RecreateCompaniesAndEmployeesTables));
        
        string IMigrationMetadata.Id
        {
            get { return "201312182359195_RecreateCompaniesAndEmployeesTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
